# Generated by Django 5.2.4 on 2025-09-13 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregationUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100)),
                ('mms_name', models.CharField(max_length=100, unique=True)),
                ('w_code', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommerceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('report', models.JSONField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mms_name', models.CharField(max_length=100, unique=True)),
                ('x_code', models.CharField(max_length=16, unique=True)),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100)),
                ('mms_name', models.CharField(max_length=100, unique=True)),
                ('w_code', models.CharField(max_length=16, unique=True)),
                ('p_min', models.IntegerField()),
                ('p_max', models.IntegerField()),
                ('aggregation_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aggregator.aggregationunit')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stations', to='aggregator.company')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('schedule', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aggregator.station')),
            ],
        ),
    ]
